---
# tasks file for ansible/roles/nginx_install
- name: create dicrectories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ docker_compose_directory }}"

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - {src: docker-compose.main.yml.j2, dest: "{{docker_compose_directory}}/docker-compose.main.yml"}
    - {src: docker-compose.yml.j2, dest: "{{ docker_compose_directory }}/docker-compose.yml"}

- name: start docker-compose on main
  shell: "docker-compose -f {{ docker_compose_directory }}/docker-compose.main.yml up -d"
  when: inventory_hostname == ansible_play_hosts[0]

- name: start docker-compose
  shell: "docker-compose -f {{ docker_compose_directory }}/docker-compose.yml up -d"
  when: inventory_hostname != ansible_play_hosts[0]