---
# defaults file for ansible/roles/nginx_install
postgres_host: db
patroni_superuser_username: root
patroni_superuser_password: password
docker_compose_directory: nextcloud
nextcloud_data_directory: /nextcloud_data
nextcloud_config_directory: /nextcloud_config