- name: ensure postgresql service stopped
  systemd:
    name: postgresql
    state: stopped
    enabled: no

- name: create patroni config directory
  file:
    path: /etc/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: 0755

- name: copy patroni.yml
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: 0755
  notify: restart patroni.service

- name: copy patroni.service
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: 0755
  notify: restart patroni.service