---
# tasks file for ansible/roles/nginx_install
- name: create dicrectories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - postgres

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - {src: docker-compose.yml, dest: postgres/docker-compose.yml}
    - {src: db.env, dest: postgres/db.env}

- name: start docker-compose
  shell: "docker-compose -f postgres/docker-compose.yml up -d"