---
# defaults file for ansible/roles/patroni
patroni_scope_name: patroni
patroni_namespace_name: service

etcd_servers: "{{ groups['etcd'] | map('extract', hostvars, ['ansible_host']) | join(':2379,') }}:2379"