version: '3'

services:
  web:
    image: nginx:1.21-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - acme:/opt/www/acme

volumes:
  acme: