---
# tasks file for ansible/roles/nginx_install
- name: create dicrectories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0775
  loop:
    - { path: "{{ docker_compose_directory }}", owner: root, group: root }
    - { path: "{{ docker_compose_directory }}/nginx.conf.d", owner: root, group: root }
    - { path: "{{ nextcloud_data_directory }}", owner: root, group: docker }

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - {src: nginx/nginx.conf.d/nextcloud.conf.j2, dest: "{{ docker_compose_directory }}/nginx.conf.d/nextcloud.conf"}
    - {src: nginx/nginx.conf, dest: "{{ docker_compose_directory }}/nginx.conf"}
    - {src: haproxy/haproxy.cfg.j2, dest: "{{ docker_compose_directory }}/haproxy.cfg"}
    - {src: docker-compose.yml.j2, dest: "{{ docker_compose_directory }}/docker-compose.yml"}
    - {src: nextcloud.env.j2, dest: "{{ docker_compose_directory }}/nextcloud.env"}

- name: start docker-compose
  shell: "docker-compose -f {{ docker_compose_directory }}/docker-compose.yml up -d"
  when: inventory_hostname == ansible_play_hosts[0]