---
# tasks file for ansible/roles/nginx_install
- name: create dicrectories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - nextcloud
    - nextcloud/nginx.conf.d

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - {src: nginx.conf.d/nextcloud.conf.j2, dest: nextcloud/nginx.conf.d/nextcloud.conf}
    - {src: docker-compose.yml.j2, dest: nextcloud/docker-compose.yml}
    - {src: nginx.conf, dest: nextcloud/nginx.conf}
    - {src: db.env, dest: nextcloud/db.env}

- name: start docker-compose
  shell: "docker-compose -f nextcloud/docker-compose.yml up -d"